stages:
  - test
  - format
test:
  stage: test
  image: python:3.10
  script:
    - cd backend
    - pip install -r requirements.txt
    - python manage.py makemigrations
    - python manage.py migrate
    - python manage.py test

prettier:
  stage: format
  image: node:latest
  script:
    - cd frontend
    - npm install
    - npx prettier '**/*.{js,css,md}' --write

